tools/jenkins/README.md

Signed-off-by: Jeremy Ho <jujaga@gmail.com>
This capitalizes some headers in a readme.

Update a readme test

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/ConfigForm.vue
frontend/src/components/GetToken.vue
frontend/src/components/Home.vue
frontend/src/main.js
frontend/src/store.js

Added Vuex to project and integrated state management via vuex into the 2 components.

Pull in Vuex iteration of application, including some UI tweaks

---

frontend/src/components/ConfigForm.vue
frontend/src/components/GetToken.vue

Fix linting

---

frontend/src/components/ConfigForm.vue
frontend/src/components/GetToken.vue
frontend/src/components/Home.vue

Fix a couple linting issues. Switch to mapGetters shorthand to fetch from store

Fix some linting issues and clean up

---

Jenkinsfile
Jenkinsfile.cicd
openshift/README.md
openshift/frontend-static.bc.yaml
openshift/frontend-static.dc.yaml
openshift/frontend.bc.yaml

This PR tests and adds PR based functionality to the Jenkins pipeline, and should deploy an environment on Openshift with the following url pattern: https://pr-##-frontend-k8vopl-dev.pathfinder.gov.bc.ca or similar.

Templated Pull Request based pipeline support

---

Jenkinsfile
Jenkinsfile.cicd

Bugfix improper source references from git in Jenkinsfile template.

Fix source repo reference on non-PR based triggers

---

Jenkinsfile
Jenkinsfile.cicd
openshift/frontend-static.dc.yaml

This PR attempts to add support for Jenkins to report back to Github regarding pipeline stage status.

Add Github/Jenkins notification integration

---

Jenkinsfile
Jenkinsfile.cicd

This PR should enable Jenkins to report build status to ALL commits, not just ones in PRs.

Bugfix NPE in main pipeline

---

Jenkinsfile
Jenkinsfile.cicd
README.md
frontend/package-lock.json
frontend/package.json
frontend/src/components/ConfigForm.vue
frontend/src/components/ConfigGeneratedJson.vue
frontend/src/components/GetToken.vue
frontend/src/components/Header.vue
frontend/src/components/Home.vue
frontend/src/components/ManualConfig.vue
frontend/src/store.js
frontend/tests/unit/components/Header.spec.js
openshift/frontend-static.dc.yaml

v0.0.2-alpha version of the GETOK UI
Add new components for user form entry of application configurations and JSON rendering of that.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-79
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-71

Initial work on 0.0.2 alpha ui

---

frontend/src/components/ConfigForm.vue
frontend/src/components/ConfigGeneratedJson.vue
frontend/src/components/GetToken.vue
frontend/src/components/Home.vue
frontend/src/store.js

Add the section where the user picks how they want to proceed with deployment.
Add the api call to POST the app config

Add the deployment section of the app config form

---

openshift/frontend.bc.yaml

This PR attempts to update the s2i base image from nodejs 8 to nodejs 10.

Change s2i image from nodejs-8-rhel7 to nodejs-10

---

frontend/src/components/ConfigGeneratedJson.vue

Enable the button that will download the contents of the Application Configuration field.
Add a function that handles clicks from the download button by starting a download named 'applicationConfiguration.json'
Solution for
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-126
Solution from this answer https://stackoverflow.com/a/18197341/324672

Json download capability

---

Jenkinsfile
Jenkinsfile.cicd

This PR adds promotion and deployment functionality to the pipelines.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-127

Implement parameterized pipeline deploy steps

---

.github/pull_request_template.md
frontend/src/components/ConfigForm.vue

Wording tweaks

---

frontend/babel.config.js
frontend/package.json
frontend/src/App.vue
frontend/src/components/ApiCheck.vue
frontend/src/components/ConfigForm.vue
frontend/src/components/ConfigGeneratedJson.vue
frontend/src/components/Footer.vue
frontend/src/components/GetToken.vue
frontend/src/components/Home.vue
frontend/src/components/ManualConfig.vue
frontend/src/main.js
frontend/src/plugins/vuetify.js
frontend/src/store.js
frontend/src/utils/constants.js
frontend/tests/unit/.eslintrc.js
frontend/tests/unit/components/Footer.spec.js
frontend/tests/unit/components/Header.spec.js
frontend/tests/unit/globalSetup.js
frontend/tests/unit/utils/utils.spec.js
frontend/vue.config.js

Add new eslint configuration to frontend app. Ran with lint fix to alter existing files.
Using same lint pattern as backend

Alter frontend linting and fix all errors

---

.gitignore
Jenkinsfile
Jenkinsfile.cicd
README.md
backend/app.js
backend/bin/www
backend/components/checks.js
backend/components/utils.js
backend/config/custom-environment-variables.json
backend/config/default.json
backend/docs/v1.api-spec.yaml
backend/package-lock.json
backend/package.json
backend/routes/v1.js
backend/routes/v1/checks.js
backend/routes/v1/routes/checks.js
backend/routes/v1/v1.js
openshift/README.md
openshift/backend.dc.yaml

This PR adds configuration support for the backend and basic node logging
- Simplify health check -> remove /checks/health endpoint
- Add morgan and npmlog based logging support
- Add unhandled rejection protection
- Implements endpoint status checking
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-77
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-78

Add configuration support and endpoint status checking

---

frontend/package.json

Vetur annoyingly sets double quotes as a formatting default. Since it's JS formatter defaults to prettier we can fix this by setting a prettier config to use single spaces (to agree with our eslint defaults).
See
https://github.com/vuejs/vetur/issues/986

Set a prettierrc config for vetur

---

backend/components/checks.js
backend/components/utils.js
backend/docs/v1.api-spec.yaml
backend/routes/v1/checks.js

This PR completes implementation of the /checks/status endpoint

Implement /checks/status endpoint

---

frontend/Caddyfile
frontend/vue.config.js
openshift/backend.bc.yaml
openshift/frontend.bc.yaml

Add publicPath support for subpath issues
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-55

Add publicPath support for subpath issues

---

backend/components/checks.js
backend/docs/v1.api-spec.yaml
frontend/src/components/HealthCheck.vue
frontend/src/components/Home.vue

Add the name of the health check endpoint to the api and frontend

Health check name

---

Jenkinsfile
Jenkinsfile.cicd
backend/app.js
backend/components/checks.js
backend/components/utils.js
backend/config/custom-environment-variables.json
backend/config/default.json
backend/package-lock.json
backend/package.json
backend/routes/auth.js
backend/routes/v1/checks.js
frontend/Caddyfile
openshift/README.md
openshift/backend.dc.yaml
openshift/frontend-static.dc.yaml

This PR implements the following:
* Implement minimally viable OIDC authentication flow
* Add pipeline and template changes for configmap and secret handling
* Add a log style to use the calling function name as prefix
* Adds routing to handle both / and /getok paths
[[SHOWCASE-152]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-152)

Implement Keycloak OIDC flow support to Backend

---

backend/components/appConfig.js
backend/components/utils.js
backend/docs/v1.api-spec.yaml
backend/package-lock.json
backend/package.json
backend/routes/v1/appConfigForm.js
backend/routes/v1/checks.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/ConfigForm.vue
frontend/src/store.js

Generate the service client password on the API side and return it to the UI.
Use asymetric encryption to only reveal the generated PW to the user's current session.
Show password on a popup (and allow decryption) after successful config change.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-83
Documentation of password generation technique will be created in this issue
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-170
For RSA key creation the following library is used for now
https://github.com/wwwtyro/cryptico
Password generation is done with the following library
https://www.npmjs.com/package/generate-password

Password encryption feature

---

frontend/vue.config.js

This bugfix allows the api and authentication to be proxied correctly in developer mode.

Fix Vue proxy config to handle multiple api paths

---

README.md

added summary details for GETOK

added summary details for GETOK

---

frontend/README.md

Readme changes for the frontend

Frontend Readme

---

README.md
backend/README.md
docs/developer-guide.md
docs/overview.md
openshift/README.md

This PR adds and updates general documentation for the get-token codebase.
[SHOWCASE-168](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-168)

Update backend documentation

---

backend/src/components/utils.js
backend/src/routes/auth.js
backend/src/routes/v1/appConfigForm.js
backend/src/routes/v1/checks.js
frontend/src/components/ConfigForm.vue
frontend/src/utils/constants.js

This PR implements logic to ensure that only users with the correct roles are able to submit acronyms. This removes the need for the temporarily hardcoded check for MSSC and DOMO acronyms; instead we now rely on Keycloak's JWT to enforce.
[SHOWCASE-58](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-58)
This PR requires that Keycloak has the acronym roles implemented. Otherwise form submission will fail due to lack of permissions.

Implement role based access control for acronyms

---

Jenkinsfile
Jenkinsfile.cicd

This PR modifies the Jenkins pipeline so that does not have a persistent worker allocated between stages.

Update pipeline to have different workers between stages

---

Jenkinsfile
Jenkinsfile.cicd
backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json
sonar-runner/build.gradle

In order to display the test failures for a unit test run in SonarQube we need to write a file that includes results other than just coverage.

Add package to write jest execution results

---

README.md
tools/README.md
tools/jenkins/Jenkinsfile

This PR adds SonarQube badges and updates the tools documentation regarding Jenkins and SonarQube setup.
[SHOWCASE-81](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-81)
[SHOWCASE-191](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-191)

Add SonarQube badges and Update tools documentation

---

Jenkinsfile
Jenkinsfile.cicd
backend/README.md
backend/config/custom-environment-variables.json
backend/config/default.json
backend/src/components/appConfig.js
backend/src/components/auth.js
backend/src/components/checks.js
backend/src/components/utils.js
backend/src/docs/v1.api-spec.yaml
backend/src/routes/v1/appConfigForm.js
backend/src/routes/v1/checks.js
frontend/src/components/ConfigForm.vue
frontend/src/store/modules/configForm.js
openshift/README.md
openshift/backend.dc.yaml

Add options to send app config to test and prod.
Adds API changes and pipeline changes for configuration of test and prod environments.
Adds the dropdown as part of step2 in the UI.
New feature (non-breaking change which adds functionality) 

Allow promotion to test and prod

---

frontend/package-lock.json
frontend/src/components/ConfigForm.vue
frontend/src/components/HealthCheck.vue
frontend/src/store/modules/auth.js
sonar-project.properties

This PR adds a GETOK application acronym registration button and surrounding step flow to ensure compliance.
This adds an interim flow to allow users to know how to get acronym approval permissions.
[SHOWCASE-194](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-194)

Add permissions step and registration button

---

backend/app.js
backend/config/test.json
backend/package-lock.json
backend/package.json
backend/src/components/appConfig.js
backend/src/components/auth.js
backend/src/components/checks.js
backend/src/components/utils.js
backend/src/routes/auth.js
backend/src/routes/v1/appConfigForm.js
backend/tests/test.spec.js
backend/tests/unit/.eslintrc.js
backend/tests/unit/components/appConfig.spec.js
backend/tests/unit/components/auth.spec.js
backend/tests/unit/components/checks.spec.js
backend/tests/unit/components/utils.spec.js
backend/tests/unit/routes/auth.spec.js
backend/tests/unit/routes/v1.spec.js
frontend/package.json
frontend/src/common/authService.js
frontend/src/components/Header.vue
frontend/src/store/modules/auth.js
sonar-project.properties

This PR adds "most" unit testing for the backend, complete with axios and class mocking.
This is needed in order to improve code quality.
[SHOWCASE-175](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-175)
[SHOWCASE-151](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-151)

Add backend unit test coverage

---

frontend/src/components/Header.vue
frontend/src/components/Home.vue
frontend/src/store/index.js

Hide the API Debugger and the token link by default.
To show them, type the konami code on the ui, or use the vue dev tools in browser to modify the vuex state to set a new devMode state to true.
Instructions for enabling devMode:
**1**
On the page, type the konami code (Enter instead of Start).
Implementation uses a array spliced to the length of the code's keystrokes to function as a queue.
**2**
- Should already have the Vue devtools set up and enabled. https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd
- Inspect the page, go to Vue
- Go to Vuex and Load State
- Set the devMode state to true and hit the save icon

Add a devMode to hide things users shouldn't see

---

openshift/patroni.dc.yaml

We likely do not need that much PV space for our database even in production. Allocation failed due to low available volume space a few hours ago. Reducing claim size in order to reduce our footprint and reduce likelihood of PVC allocation failure.

Reduce PVC size from 5 to 2gb

---

openshift/backend.bc.yaml
openshift/frontend-static.bc.yaml
openshift/frontend.bc.yaml

This PR makes intermediary cached images periodically look for and pull updates from upstream.
This is so that any upstream security fixes will trickle their way down to our build images.

Set local cached images to periodically schedule updates from sources

---

backend/config/custom-environment-variables.json
backend/config/default.json
backend/config/test.json
backend/package-lock.json
backend/package.json
backend/src/components/keyCloakServiceClientMgr.js
backend/src/components/realmAdminSvc.js
backend/src/docs/v1.api-spec.yaml
backend/src/routes/v1.js
backend/src/routes/v1/kcClientForm.js
backend/tests/unit/components/keyCloakServiceClientMgr.spec.js
backend/tests/unit/components/realmAdminSvc.spec.js
backend/tests/unit/routes/v1.spec.js
openshift/README.md
openshift/backend.dc.yaml

Initial commit of KeyCloak Realm Administration
Add endpoint for creating/updating a Service Client in KeyCloak to use a Common Service (also in KeyCloak).
Update api documents for endpoint, and OpenShift documents for secrets and configuration.

KeyCloak Realm Service Clients

---

Jenkinsfile
Jenkinsfile.cicd
openshift/README.md

We added a new secret for KeyCloak realm, so we need to add a check in our Jenkins deployments that the expected secret has been added to the environment.

Add check for secret before deployment

---

backend/config/custom-environment-variables.json
backend/config/default.json
backend/config/test.json
backend/src/components/appConfig.js
backend/src/docs/v1.api-spec.yaml
backend/src/routes/v1/appConfig.js
backend/src/routes/v1/appConfigForm.js
backend/src/routes/v1/kcClientForm.js
backend/tests/unit/components/appConfig.spec.js
backend/tests/unit/components/keyCloakServiceClientMgr.spec.js
backend/tests/unit/components/realmAdminSvc.spec.js
frontend/package-lock.json
frontend/package.json
frontend/public/files/ches.postman_collection.json
frontend/src/common/apiService.js
frontend/src/components/ConfigForm.vue
frontend/src/components/ConfigGeneratedJson.vue
frontend/src/components/Home.vue
frontend/src/components/WebAdeVisualizer.vue
frontend/src/store/index.js
frontend/src/store/modules/configForm.js
frontend/src/store/modules/webadeVisualizer.js
frontend/src/utils/commonServices.js
frontend/src/utils/constants.js
package-lock.json

CHES access grant:
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-245
Text Tweak:
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-280
New feature (non-breaking change which adds functionality) 
Breaking change (fix or feature that would cause existing functionality to change) 
Will need in your local json the Keycoak info for each realm (GETOK KC realm, dev, test, prod)
"keyCloak": {
"DEV": {
"endpoint": "SC_KC_INT_ENDPOINT",
"username": "SC_KC_INT_USERNAME",
"password": "SC_KC_INT_PASSWORD",
"realm": "SC_KC_INT_REALM"
}

GETOK diff/keycloak/visualizer features

---

frontend/src/components/ConfigForm.vue
frontend/src/components/ConfigGeneratedJson.vue
frontend/src/components/Home.vue
frontend/src/components/WebAdeVisualizer.vue
frontend/src/store/modules/auth.js
frontend/src/store/modules/webadeVisualizer.js
frontend/src/utils/commonServices.js
frontend/tests/unit/components/ConfigGeneratedJson.spec.js
frontend/tests/unit/store/modules/checks.spec.js
frontend/tests/unit/store/modules/configForm.spec.js

Fixes/improvements for getok from the tickets shown below (see them for details)
Tickets:
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-293
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-290
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-291
Bug fix (non-breaking change which fixes an issue) 

UI improvements for GETOK

---

frontend/babel.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.vue
frontend/src/components/ApiCheck.vue
frontend/src/components/ConfigForm.vue
frontend/src/components/ConfigGeneratedJson.vue
frontend/src/components/Footer.vue
frontend/src/components/Header.vue
frontend/src/components/HealthCheck.vue
frontend/src/components/Home.vue
frontend/src/components/WebAdeVisualizer.vue
frontend/src/main.js
frontend/src/plugins/vuetify.js
frontend/tests/unit/components/App.spec.js
frontend/tests/unit/components/Footer.spec.js
frontend/tests/unit/components/Header.spec.js
frontend/tests/unit/globalSetup.js
package-lock.json

Upgrade Vue CLI to 4.
Upgrade from Vuetify 1.5 to 2.1. Refactor app to use new framework.
Updated some other components to newer versions.
Note Vuetify switched to sass, hence the sass-loader dev install.
https://github.com/vuetifyjs/eslint-plugin-vuetify installed and configure so lint will fail on old (even if compatible) Vuetify syntax/components.

Vue-CLI/Vuetify upgrade

---

Jenkinsfile
Jenkinsfile.cicd
openshift/backend.dc.yaml
openshift/frontend-static.dc.yaml
openshift/patroni-ephemeral.dc.yaml
openshift/patroni.dc.yaml

This PR adds custom Network Security Policies to the deployment configs. Included is:
- Internal K8S API
- Backend Egress
- Patroni Cluster
This allows us to be futureproof with OCP 4.x when that goes live.
[[SHOWCASE-476]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-476)

Add custom Network Security Policies

---

openshift/frontend.bc.yaml

This is needed in order to make the build go faster (hopefully)
For some strange reason the build is hitting the 10 minute limit and killing itself.

Increase resource limits for frontend buildconfig

---

backend/src/models/acronym.js

Missing default values for acronym model

Fix bug with missing acronym default val

---

backend/tests/unit/components/appConfig.spec.js
frontend/src/common/apiService.js
frontend/src/components/ConfigForm.vue
frontend/src/store/modules/configForm.js
frontend/src/utils/constants.js
frontend/tests/unit/store/modules/configForm.actions.spec.js
frontend/tests/unit/store/modules/configForm.spec.js
openshift/README.md

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-540
Modify GETOK UI so that user selects acronym first.
Call out to GETOK API to fetch acronym details when selected, and control WebADE options based on that.

Modify Acronym selection to be in Step 1

---

frontend/public/files/cdogs.postman_collection.json

added a new postman request to return a dictionary of the supported file type conversions
allows dev's to test api endpoints
JIRA ticket:
'Update the postman collection in GETOK' (https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-606)

added /fileTypes request

---

backend/src/components/appConfig.js
backend/src/components/email.js
backend/src/components/keyCloakServiceClientMgr.js
backend/src/docs/v1.api-spec.yaml
backend/src/migrations/20200123221832-add-acronym-description.js
backend/src/models/acronym.js
backend/src/services/acronym.js
backend/tests/unit/components/acronyms.spec.js
backend/tests/unit/components/appConfig.spec.js
backend/tests/unit/components/email.spec.js
backend/tests/unit/components/keyCloakServiceClientMgr.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-659
DB Migration changes and backend changes to write Name and Description to the Acronym table in the GETOK database.
New DB field added: acronym.description
Migration Script will write "None Entered" to this field for existing acronyms created prior to this change. (we can manually update for our existing clients with desired text, can get MDS and PEN_RETRIEVAL ones from KC).
Moving this PR through first as it is stand-alone to **write** that data. Subsequent PR will address Front-End **read** to pre-populate the fields.
Added a missed unit test from the last PR (email stuff)

Preserve acronym name/decscription - backend changes

---

backend/tests/unit/components/fixtures/acronymDetail.json
frontend/src/components/ConfigForm.vue
frontend/tests/unit/store/modules/configForm.actions.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-613
Change the Vue app to pre-populate the acronym name and description from the database.
Add an unrelated missing Unit Test.

Front end changes to pull in saved Acronym Name/Description

---

frontend/src/components/RegistrationForm.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-633
- changed wording in 'Register New App' form/error/success messages
Waiting for confirmed changes to UI after UX review later this week

Preliminary changes to wording

---

frontend/package-lock.json
frontend/package.json

Too many dependencies. Turns out we don't need Jest, Vue testing has it.

Remove Jest

---

backend/src/components/audit.js
backend/src/docs/v1.api-spec.yaml
backend/src/services/audit.js
backend/src/services/index.js

Populate DB call for getting audit history.
This schema will change with new history setup after UX decisions, so not permanent, but structure in place now.

DB queries for getting audit history by acronym

---

backend/app.js
backend/config/database.js
backend/package-lock.json
backend/package.json
backend/src/components/acronyms.js
backend/src/components/appConfig.js
backend/src/components/audit.js
backend/src/components/auth.js
backend/src/components/permissionHelpers.js
backend/src/components/utils.js
backend/src/routes/auth.js
backend/src/routes/v1/acronyms.js
backend/src/routes/v1/audit.js
backend/src/routes/v1/keyCloak.js
backend/src/routes/v1/webAde.js
backend/src/services/user.js
backend/tests/unit/components/appConfig.spec.js
backend/tests/unit/components/keyCloakServiceClientMgr.spec.js
backend/tests/unit/components/permissionHelpers.spec.js
backend/tests/unit/components/utils.spec.js
frontend/package-lock.json
frontend/package.json

This PR changes user acronym permission checking behavior to check from the DB instead of from the JWT roles. This refactor is necessary in order to allow enable upcoming UI changes. The list of user acronyms is jury-rigged into the existing /auth/token endpoint for now, but will likely be migrated to its own discrete endpoint at a later date.
[SHOWCASE-714](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-714)

Refactor backend to check user acronym permissions from DB

---

backend/src/components/auth.js
frontend/src/App.vue
frontend/src/common/apiService.js
frontend/src/components/ConfigForm.vue
frontend/src/router.js
frontend/src/store/index.js
frontend/src/store/modules/auth.js

This PR completes the first phase of transitioning user acronym knowledge from the JWT to the DB. The main change on this PR is that the frontend now draws acronym information from the /auth/token endpoint.
Other Changes:
* Enable lazy-load support for Home page router
* Change JWT access-token to be stored in session-storage
* Attempt to fix refresh token flow bug
* Remove uninstantiated acronymRadios v-model reference error
[SHOWCASE-710](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-710)
[SHOWCASE-718](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-718)

Update frontend to populate acronyms from /auth/token endpoint

---

frontend/src/components/RegistrationForm.vue

Show user's email address in add new app success message.
this is an amendment to PR119 where success message was showing variable.
To test, register a new app and ensure your email address shows in success dialog.

evaluate variable in register success message

---

Jenkinsfile
Jenkinsfile.cicd
openshift/commonPipeline.groovy
openshift/patroni-ephemeral.dc.yaml

This PR refactors the existing Jenkins pipelines so that it achieves the following:
* Main branches (feature-refactor, master, etc) will deploy correctly with the right parameterization
* Reduced code duplication by consolidating logic into a common pipeline groovy file
This PR also lowers the CPU Limit of Patroni Ephemeral pods from 1 core to 500 millicores.
[SHOWCASE-758](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-758)

Minor Jenkins Pipeline Refactor

---

Jenkinsfile
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/base/BaseAuthButton.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/main.js
app/frontend/src/router/index.js
app/frontend/src/store/index.js

This PR adds vuex and an empty store to the baseline frontend framework.
Other fixes:
* Change auth button to white outlined style
* Change router to force redirect to /home instead of aliasing as /
* Reduce specificity of navbar path highlighting
* Fix axios $httpApi baseURL misconfiguration
[SHOWCASE-761](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-761)

Add Vuex to Frontend and minor bugfixes

---

app/frontend/.env
app/frontend/.env.development
app/frontend/.env.test
app/frontend/src/components/Welcome.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/router/index.js
app/frontend/src/utils/commonServices.js
app/frontend/src/views/About.vue
app/frontend/src/views/Home.vue
app/frontend/tests/unit/components/Welcome.spec.js
app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
app/frontend/tests/unit/views/About.spec.js

supports: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-748
mockup: https://www.figma.com/proto/PqqxnXfahmDGJYC74fj1bQ/onboarding_v5?scaling=min-zoom&node-id=30%3A60
-added a 'welcome' component to show on the home page
-the header, footer, nav were done as part of the skeleton app.
-contains a list of common services that is pulled from a utils/commonServices.js object.

Refactor homepage

---

app/.sequelizerc
app/app.js
app/jest.config.js
app/lcov-fix.js
app/package-lock.json
app/package.json
app/src/migrations/20190729000000-initialize-database.js
app/src/migrations/20200107052720-add-acronym-webade-flag-columns.js
app/src/migrations/20200123221832-add-acronym-description.js
app/src/models/acronym.js
app/src/models/index.js
app/src/models/lifecycle.js
app/src/models/lifecyclehistory.js
app/src/models/user.js
app/src/models/useracronym.js
app/src/services/acronym.js
app/src/services/audit.js
app/src/services/index.js
app/src/services/lifecycle.js
app/src/services/user.js
openshift/app.bc.yaml
openshift/app.dc.yaml

This PR reintroduces sequelize and the existing DB model and migrations from the old backend. This is a prerequisite to restoring backend API functionality.
**Other Changes:**
* Security Advisory fix: https://www.npmjs.com/advisories/1488
* Update jest to 25.x and implement lcov fix: https://stackoverflow.com/q/60323177
* Restore pre-lifecycle hook for deployment migrations
[SHOWCASE-760](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-760)

Restore DB connectivity in backend app

---

app/frontend/src/components/ApplicationList.vue
app/frontend/src/components/base/BaseActionCard.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-765
Style the new cards and add them in a foreach loop.
Still dummy data. Merging this in in the interest of having small manageable PRs.

Ui for application cards

---

app/frontend/src/components/ApplicationList.vue
app/frontend/src/services/userService.js
app/frontend/src/store/index.js
app/frontend/src/store/modules/user.js
app/frontend/tests/unit/components/ApplicationList.spec.js
app/frontend/tests/unit/services/userService.spec.js
app/frontend/tests/unit/store/index.spec.js
app/frontend/tests/unit/store/modules/user.actions.spec.js
app/frontend/tests/unit/store/modules/user.spec.js
app/frontend/tests/unit/views/Application.spec.js
app/frontend/tests/unit/views/MyApps.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-765
Add in the vuex store module for users and return the acronym data (still dummy in this iterative PR) from there rather than in the component.
Add required unit tests for stuff added as part of this ticket.

Set up calling acronym data from store. Add unit tests

---

app/frontend/src/components/base/BaseAuthButton.vue
app/frontend/src/router/index.js
app/package-lock.json
app/package.json
app/src/components/users.js
app/src/docs/v1.api-spec.yaml
app/src/routes/v1.js
app/src/routes/v1/users.js
app/src/services/user.js
app/tests/unit/components/users.spec.js
app/tests/unit/routes/v1.spec.js
app/tests/unit/routes/v1/users.spec.js

This PR implements the /users/:keycloakId/acronyms endpoint.
A routing bug on the frontend was also fixed.
[SHOWCASE-853](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-853)

Implement getUserAcronym Endpoint

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/HelloCall.vue
app/frontend/src/main.js
app/frontend/src/services/helloService.js
app/frontend/src/services/index.js
app/frontend/src/services/interceptors.js
app/frontend/src/services/userService.js
app/frontend/src/store/modules/user.js
app/frontend/tests/unit/services/helloService.spec.js
app/frontend/tests/unit/services/userService.spec.js
app/frontend/tests/unit/store/modules/user.actions.spec.js

This PR implements the frontend API service layer structure we intend to use for all client-side calls to our backend server. This is needed in order to ensure there is a separation of concerns between components and API call logic.
**Other Changes**
* Add axios-mock-adapter and associated tests
[SHOWCASE-853](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-853)

Implement Frontend Service Layer structure

---

Jenkinsfile
app/config/custom-environment-variables.json
app/config/default.json
app/config/test.json
app/package-lock.json
app/package.json
app/src/components/email.js
app/src/components/utils.js
app/src/docs/v1.api-spec.yaml
app/src/routes/v1.js
app/src/routes/v1/email.js
app/src/routes/v1/users.js
app/tests/unit/components/email.spec.js
app/tests/unit/components/utils.spec.js
app/tests/unit/routes/v1/email.spec.js
app/tests/unit/routes/v1/hello.spec.js
openshift/README.md
openshift/app.dc.yaml

This PR reimplements the `/email` endpoint of GETOK. This is a prerequisite for the Request Account form to work as intended.
**Other Changes**
* Added new service client config structure
* Update OpenAPI spec with more templates and validation error component support
* Added `axios-mock-adapter` to app dev dependencies
[SHOWCASE-840](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-840)

Reimplement /email endpoint in GETOK backend

---

app/frontend/src/components/ApplicationList.vue
app/frontend/src/services/userService.js
app/frontend/src/store/modules/user.js
app/src/components/users.js
app/src/docs/v1.api-spec.yaml
app/src/routes/v1/users.js

Put in the structure to display KeyCloak client status
This uses hard coded dummy data to get the spec and scaffold and UI in. Next PR will include backend impl and UTs.
Hard coded to only have (fake) client data for WORG and MSSC in this impl.
Can just review code and test it out fuller on the next PR.

Display service client status (with dummy data)

---

app/frontend/public/index.html
app/frontend/src/assets/scss/style.scss
app/frontend/src/components/Welcome.vue
app/frontend/src/components/base/BaseSecure.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue

final change (for now) to typography to get headings and paragraphs to match bcgov design guidelines.
as seen here:
https://developer.gov.bc.ca/Design-System/Typography
(not the best looking website)
thought this was worth doing now as it will affect spacing of new components

fixed line height and headings inline with bcgov style guide

---

app/frontend/src/components/JWTDialog.vue
app/frontend/src/components/RequestForm.vue
app/frontend/src/components/base/BaseDialog.vue
app/frontend/src/store/modules/auth.js
app/frontend/src/views/Admin.vue
app/frontend/tests/unit/components/JWTDialog.spec.js
app/frontend/tests/unit/components/RequestForm.spec.js
app/frontend/tests/unit/components/base/BaseDialog.spec.js
app/frontend/tests/unit/store/modules/auth.getters.spec.js
app/frontend/tests/unit/views/Admin.spec.js

This PR adds basic JWT Token lookup support in the Admin panel. It is designed to allow administrative users to be able to acquire and inspect their current JWT token.
**Other Changes**
- Extend auth store with sfullName, userName and token getters
- Update requestForm to use userName getter
- Bugfix BaseDialog component to emit closeDialog event when clicking outside
[SHOWCASE-871](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-871)

Add JWT Token support to admin page

---

app/frontend/src/components/RequestForm.vue
app/frontend/src/components/apiAccess/ApiAccess.vue
app/frontend/src/components/apiAccess/Step1.vue
app/frontend/src/components/apiAccess/Step2.vue
app/frontend/src/components/apiAccess/Step3.vue
app/frontend/src/components/apiAccess/Step4.vue
app/frontend/src/store/index.js
app/frontend/src/store/modules/apiAccess.js
app/frontend/src/views/Application.vue
app/frontend/tests/unit/store/modules/apiAccess.getters.spec.js
app/frontend/tests/unit/store/modules/apiAccess.mutations.spec.js

WIP structure for 
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-766
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-767
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-768
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-769
Add the views and navigation and components for the API access form in skeleton, and the backing Vuex store.
Would like to get feedback/review on this before proceeding with getting all the other stuff in, and to get it integrated into the code base.

Skeleton structure of API Access components

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/assets/scss/style.scss
app/frontend/src/components/apiAccess/ApiAccess.vue
app/frontend/src/components/apiAccess/Step2.vue
app/frontend/src/components/apiAccess/Step3.vue
app/frontend/src/services/acronymService.js
app/frontend/src/services/keycloakService.js
app/frontend/src/store/modules/apiAccess.js
app/frontend/src/utils/constants.js
app/package-lock.json
app/package.json
app/src/components/acronyms.js
app/src/components/permissionHelpers.js
app/src/routes/v1/acronyms.js
app/src/routes/v1/keycloak.js
app/tests/unit/components/acronyms.spec.js
app/tests/unit/components/fixtures/acronymDetail.json
app/tests/unit/components/permissionHelpers.spec.js
backend/src/routes/v1/acronyms.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-767
Note: to add acronyms to yourself at this point (we will seed data later in PRs), go the admin page and in the API tester run
acronyms/<acr>/addUser/<you@idir>
like
acronyms/WORG/addUser/loneil@idir
The acronym does not have to exist in the system, this will add it if it's not there.
I've seeded WORG for you guys. It should hopefully appear in the list
Feel free to create/delete/whatever service clients for the WORG acronym.
Don't mess around with MSSC as that could affect users.
Adds the functionality to create the service clients, decrypt and show PW, etc.
Includes step 3 UI and ConfigForm POST backend call.
Some style tweaks on the existing pages are still required and Step 4 still to come.
New feature (non-breaking change which …

Step 3 of API Access

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/apiAccess/ApiAccess.vue
app/frontend/src/components/apiAccess/Step2.vue
app/frontend/src/components/apiAccess/Step3.vue
app/frontend/src/components/apiAccess/Step4.vue
app/frontend/src/views/Application.vue
openshift/commonPipeline.groovy

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-769
UI and styling for API access step 4

API access step4

---

app/src/docs/v1.api-spec.yaml

Getting a quick feedback on the spec for an endpoint that will serve to populate the table on this page
https://www.figma.com/proto/PqqxnXfahmDGJYC74fj1bQ/onboarding_v5?node-id=30%3A926&scaling=min-zoom
So for an acronym, get me all the users associated and their relevant details.
Will call DB for UserAcronym mapping, then KC for all the user fields.
Docs:
https://getok-dev.pathfinder.gov.bc.ca/pr-160/api/v1/docs#operation/getAcronymUsers

Acronyms/users endpoint (spec approval)

---

app/src/components/acronyms.js
app/src/components/keyCloakServiceClientMgr.js
app/src/components/realmAdminSvc.js
app/src/components/users.js
app/src/routes/v1/acronyms.js
app/src/services/acronym.js
app/tests/unit/components/acronyms.spec.js
app/tests/unit/components/fixtures/acronymUsers.json
app/tests/unit/components/fixtures/keycloakUsers.json
app/tests/unit/components/keyCloakServiceClientMgr.spec.js
app/tests/unit/components/realmAdminSvc.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-774
Add the implementation of the acronyms//users endpoint.
Permission required for an acronym to call it.
Can test in the API tester with
acronyms/WORG/users
Altered the Keycloak management classes to take a filter in for getting users, though this one just fetches all KC users on the backend and then filters based on acronym mapping.
Could call endpoint once per user but that would be much more inefficient.

API for acronym user fetch

---

app/frontend/src/assets/scss/style.scss
app/frontend/src/components/RequestForm.vue
app/frontend/src/components/Welcome.vue
app/frontend/src/components/admin/ApiTester.vue
app/frontend/src/components/admin/HealthDialog.vue
app/frontend/src/components/admin/JWTDialog.vue
app/frontend/src/components/apiAccess/Step1.vue
app/frontend/src/components/apiAccess/Step2.vue
app/frontend/src/components/apiAccess/Step3.vue
app/frontend/src/components/apiAccess/Step4.vue
app/frontend/src/components/base/BaseActionCard.vue
app/frontend/src/components/base/BaseAuthButton.vue
app/frontend/src/components/base/BaseDialog.vue
app/frontend/src/components/base/BaseSecure.vue
app/frontend/src/components/bcgov/BCGovFooter.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/views/Admin.vue
app/frontend/src/views/NotFound.vue
app/frontend/src/views/RequestAccount.vue
app/frontend/tests/unit/components/RequestForm.spec.js
app/frontend/tests/unit/components/base/BaseAuthButton.spec.js
app/frontend/tests/unit/components/base/BaseSecure.spec.js
app/frontend/tests/unit/views/RequestAccount.spec.js
frontend/src/components/ApiCheck.vue
frontend/src/components/Dialog.vue
frontend/src/components/RegistrationForm.vue

This PR resolves a large number of various style fixes to better align with BCGov Design principles. This is needed in order to ensure accessibility requirements are met.
- Vertically center the request account form button texts
- Link text underline should only show on hover
- Home page card tweaks
- My Applications page - card rounding
- Revisit read-only visual indications on read-only idir and email fields
- Confirm if RequestForm submit button be disabled until form is valid
- Request Account page spacing
- Button icons have underlines when hovered
[SHOWCASE-881](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-881)

Update various styles to better align with BCGov Design

---

app/frontend/src/components/Team.vue
app/frontend/src/services/acronymService.js
app/frontend/src/views/Application.vue
app/frontend/tests/unit/components/Team.spec.js
app/frontend/tests/unit/services/acronymService.spec.js
app/frontend/tests/unit/services/fixtures/acronymUsers.json
frontend/package.json

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-774
Populate table in the Team tab on load of components with the result from the acronyms/<acr>/users call.
Update vuetify.
To test, go to one of the pre-populated acronyms in the PR and look in the Team tab.
Can see a fresh acronym by adding new one at the admin API tester with
/acronyms/<new acr>/yourname@idir

Team tab table

---

README.md

The badges on the top-level readme were still referencing the wrong project key. This PR fixes that.

Fix incorrect image references for SonarQube badges

---

app/src/routes/v1/acronyms.js

Introduced in last PR, I typo'd an existing parameter name somehow that broke to service client per acronym API call (yikes!).
Fixed with a rollback in prod so nothing broken at the moment.

Fix bug causing API Access tab actions to fail to load

---

app/frontend/src/components/RequestForm.vue
app/frontend/src/components/Resources.vue
app/frontend/src/components/Welcome.vue
app/frontend/src/components/apiAccess/Step4.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/router/index.js
app/frontend/src/views/Documentation.vue
app/frontend/tests/unit/components/Resources.spec.js
app/frontend/tests/unit/router/index.spec.js
app/frontend/tests/unit/views/Documentation.spec.js

Supports ticket: [SHOWCASE-1341](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1341)
I'm not sure if the screenshots on the Jira Ticket were approved by all.
I've changed a coupl epof the bits of wording but not sure if they are an improvement.
Let me know if you prefer the text in the screenshots.

GETOK - Integrate the CSST POSTMAN collection and instructions.

---

app/config/custom-environment-variables.json
app/config/default.json
app/config/test.json
app/src/components/email.js
app/src/components/github.js
app/src/routes/v1/email.js
app/tests/unit/components/github.spec.js
app/tests/unit/routes/v1/email.spec.js
openshift/README.md
openshift/app.dc.yaml

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1446
In the same Request Access action when the email is sent, create a Github issue in nr-get-token (using bcgov-nr-csst). Includes the same details that the email includes.
Added a personal access token new to GETOK (see Further Comments below). Used to call the Github API /issues endpoint.
https://docs.github.com/en/rest/reference/issues#create-an-issue
New personal access token created with the Parrot  (bcgov-nr-csst) for this. Only scope needed is public_repo.
**nr-csst-getok**
Can log in with Parrot and go to https://github.com/settings/tokens
Stored in openshift secret
https://console.pathfinder.gov.bc.ca:8443/console/project/k8vopl-dev/browse/secrets/getok-sc-github-issue- …

Create github issue when email is sent

---

app/frontend/public/files/cdogs.postman_collection.json
openshift/README.md
openshift/app.dc.yaml
openshift/nsp.yaml
openshift/patroni-ephemeral.dc.yaml
openshift/patroni.dc.yaml

This PR updates DGRSC links, and backfills some upcoming OCP4 changes.
[SHOWCASE-1704](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1704)

Update DGRSC Links

---

app/config/default.json
app/frontend/public/files/cdogs.postman_collection.json
app/frontend/public/files/ches.postman_collection.json
app/frontend/src/components/Resources.vue
app/frontend/src/components/apiAccess/ResourcesSidebar.vue
app/frontend/src/utils/commonServices.js
app/tests/unit/components/fixtures/token.json
backend/config/default.json
backend/tests/unit/components/fixtures/token.json
frontend/public/files/cdogs.postman_collection.json
frontend/public/files/ches.postman_collection.json
frontend/src/utils/commonServices.js
openshift/README.md

[SHOWCASE-1684](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1684)

Update default values and endpoints to OIDC

---

app/frontend/src/components/apiAccess/Step2.vue

Was using 2000 chars (webade max) not 255 (keycloak max)

Adjust length of description in FE on step 2

---

.github/workflows/unit-tests.yaml
app/frontend/src/components/apiAccess/Step2.vue

Forgot to set the actual textbox counter last time.

Set proper counter

---

app/frontend/src/components/apiAccess/Step1.vue
app/frontend/src/components/apiAccess/Step3.vue
app/frontend/src/store/modules/apiAccess.js
app/frontend/tests/unit/store/modules/apiAccess.getters.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2006
Correct OIDC link on step 4.
Fix some grammar.

Fix oidc link

---

app/frontend/src/components/apiAccess/Step2.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1996
Disclaimer in popup when creating client.

Disclaimer text

---

.codeclimate.yml
app/src/migrations/20211103174454-widen-user-username.js
openshift/app.bc.yaml

Increase username to 64 chars
See https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2258 for details
Update alpine image (like we did in other apps)
Do the same codeclimate tweak as CHEFS

Increase username to 64 chars

---

app/frontend/src/components/History.vue
app/frontend/src/services/acronymService.js
app/frontend/src/views/Application.vue
app/src/components/acronyms.js
app/src/docs/v1.api-spec.yaml
app/src/routes/v1/acronyms.js
app/src/services/deploymentHistory.js
app/tests/unit/components/acronyms.spec.js
app/tests/unit/routes/v1/acronyms.spec.js

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-778
Use the new Deployment History table to display a history tab on the acronym front end.
New feature (non-breaking change which adds functionality) 

Add history page and route

---

app/frontend/src/components/RequestForm.vue
app/frontend/src/components/admin/AccessGrant.vue
app/frontend/src/components/admin/ServiceClients.vue
app/src/components/acronyms.js
app/src/components/assets/confirmation-email-template.html
app/src/components/email.js
app/src/components/github.js
app/src/migrations/20220407224032-add-acronym-ministry.js
app/src/models/acronym.js
app/src/routes/v1/acronyms.js
app/src/routes/v1/email.js
app/src/services/acronym.js
app/tests/unit/routes/v1/email.spec.js

Capture ministry and primary contact information for the Acronym. 
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2472

Capture ministry and primary contact info

---

app/src/components/users.js
openshift/app.bc.yaml

Update Node to 16.15.0

---

app/frontend/src/components/RequestForm.vue

Add CHES notice to request form

---

app/frontend/src/components/ApplicationList.vue
app/frontend/src/components/Welcome.vue
app/frontend/src/components/bcgov/BCGovNavBar.vue
app/frontend/src/router/index.js
app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
app/frontend/tests/unit/router/index.spec.js

Jira ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2865?
Changes:
1. Putting banner on the main page.
2. Disabling 'Create App' button.
3. Removing 'Request Account' tab item and route.
4. Removing the text: “*Submit the Request Account form to add a new application”.
5. Putting the banner above the header on My App page.
6. Deleting Document page and removing from navigation bar, route deleted as well.
7. About page, disabling “Request Account” links and "Documentation" links as well, replacing with catalog site url: https://bcgov.github.io/common-service-showcase/onboarding/aps.html

Disabling create app features
